### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by dezhniuk** [dezhniuk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by duo23** [comment]
EXPERIENCE

1946
Trump was born on June 14

1964
Graduated New York Military Academy

1987
Trump published the book The Art of the Deal

1990
Trump asserted his own net worth in the neighborhood of $1.5 billion. At the time, the real estate market was in decline, reducing the value of and income from Trump's empire.

2005
Trump launched his for-profit Trump University, offering classes in real estate and acquiring and managing wealth. The venture had been under scrutiny almost since its inception and at the time of his 2015 presidential bid, it remained the subject of multiple lawsuits. 

2016
Trump became the official Republican nominee for president in the 2016 presidential election against Democrat Hillary Clinton. Defying polls and media projections, he won the majority of electoral college votes in a stunning victory on November 8, 2016. Despite losing the popular vote to Hillary Clinton by almost 2.9 million votes, Trump's electoral win — 306 electoral college votes to Clinton's 232 — clinched his victory as the 45th president of the United States.

2017
Trump signed several measures under the Congressional Review Act to reverse regulations related to education, land use and a "blacklisting rule" requiring federal contractors to disclose violations of federal labor, wage and workplace safety laws.

2018
Trump and Kim met at the secluded Capella resort in Singapore, marking the first such encounter between a sitting U.S. president and North Korean leader. The two held private talks with their interpreters, before expanding the meeting to include such top staffers as Pompeo (now U.S. secretary of state), National Security Adviser John Bolton and White House Chief of Staff John Kelly.

2019
Trump met with Prince Charles and reportedly discussed climate change at length. In an interview with British TV host Piers Morgan, Trump said "I believe that there is a change in weather and I think it changes both ways...It used to be called global warming, that wasn't working, then it was called climate change and now actually it is called extreme weather."
